// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsFLRTga6lfagrxz0TmMh_drp1S6wp_I',
    appId: '1:106972165954:web:8a008131cf8483f5edbadb',
    messagingSenderId: '106972165954',
    projectId: 'gita-app-2b6e4',
    authDomain: 'gita-app-2b6e4.firebaseapp.com',
    storageBucket: 'gita-app-2b6e4.appspot.com',
    measurementId: 'G-F3Y4NHP7N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtN_df7Bg-aD8MkHoYhp2yv9A5ovk3MnY',
    appId: '1:106972165954:android:b8252f39331ea100edbadb',
    messagingSenderId: '106972165954',
    projectId: 'gita-app-2b6e4',
    storageBucket: 'gita-app-2b6e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDMV5sMKw24jfgvtgDRluYDhlwZ-fs2Cc',
    appId: '1:106972165954:ios:9736f2dcfdc0e4a7edbadb',
    messagingSenderId: '106972165954',
    projectId: 'gita-app-2b6e4',
    storageBucket: 'gita-app-2b6e4.appspot.com',
    iosBundleId: 'com.achivie.gita.app.gitaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDMV5sMKw24jfgvtgDRluYDhlwZ-fs2Cc',
    appId: '1:106972165954:ios:65f9d5a0f87cf5b5edbadb',
    messagingSenderId: '106972165954',
    projectId: 'gita-app-2b6e4',
    storageBucket: 'gita-app-2b6e4.appspot.com',
    iosBundleId: 'com.achivie.gita.app.gitaApp.RunnerTests',
  );
}
